server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: employeeexchange
    queue: employeequeue
    routingkey: employeeroutingkey
